package model;
// Generated Oct 23, 2017 3:22:47 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaContrato generated by hbm2java
 */
@Entity
@Table(name="ta_contrato"
    ,catalog="mydb"
)
public class TaContrato  implements java.io.Serializable {


     private Integer idtContrato;
     private TbFalecido tbFalecido;
     private TbServico tbServico;

    public TaContrato() {
    }

    public TaContrato(TbFalecido tbFalecido, TbServico tbServico) {
       this.tbFalecido = tbFalecido;
       this.tbServico = tbServico;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_contrato", unique=true, nullable=false)
    public Integer getIdtContrato() {
        return this.idtContrato;
    }
    
    public void setIdtContrato(Integer idtContrato) {
        this.idtContrato = idtContrato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_falecido", nullable=false)
    public TbFalecido getTbFalecido() {
        return this.tbFalecido;
    }
    
    public void setTbFalecido(TbFalecido tbFalecido) {
        this.tbFalecido = tbFalecido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_servico", nullable=false)
    public TbServico getTbServico() {
        return this.tbServico;
    }
    
    public void setTbServico(TbServico tbServico) {
        this.tbServico = tbServico;
    }




}


