package model;
// Generated Oct 23, 2017 3:22:47 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaCompra generated by hbm2java
 */
@Entity
@Table(name="ta_compra"
    ,catalog="mydb"
)
public class TaCompra  implements java.io.Serializable {


     private Integer idtaCompra;
     private TbFalecido tbFalecido;
     private TbProduto tbProduto;

    public TaCompra() {
    }

    public TaCompra(TbFalecido tbFalecido, TbProduto tbProduto) {
       this.tbFalecido = tbFalecido;
       this.tbProduto = tbProduto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idta_compra", unique=true, nullable=false)
    public Integer getIdtaCompra() {
        return this.idtaCompra;
    }
    
    public void setIdtaCompra(Integer idtaCompra) {
        this.idtaCompra = idtaCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_falecido", nullable=false)
    public TbFalecido getTbFalecido() {
        return this.tbFalecido;
    }
    
    public void setTbFalecido(TbFalecido tbFalecido) {
        this.tbFalecido = tbFalecido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_produto", nullable=false)
    public TbProduto getTbProduto() {
        return this.tbProduto;
    }
    
    public void setTbProduto(TbProduto tbProduto) {
        this.tbProduto = tbProduto;
    }




}


