package model;
// Generated Oct 23, 2017 3:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbCemiterio generated by hbm2java
 */
@Entity
@Table(name="tb_cemiterio"
    ,catalog="mydb"
)
public class TbCemiterio  implements java.io.Serializable {


     private Integer idtCemiterio;
     private String nmeCemiterio;
     private String endCemiterio;
     private Set<TbFalecido> tbFalecidos = new HashSet<TbFalecido>(0);

    public TbCemiterio() {
    }

	
    public TbCemiterio(String nmeCemiterio, String endCemiterio) {
        this.nmeCemiterio = nmeCemiterio;
        this.endCemiterio = endCemiterio;
    }
    public TbCemiterio(String nmeCemiterio, String endCemiterio, Set<TbFalecido> tbFalecidos) {
       this.nmeCemiterio = nmeCemiterio;
       this.endCemiterio = endCemiterio;
       this.tbFalecidos = tbFalecidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_cemiterio", unique=true, nullable=false)
    public Integer getIdtCemiterio() {
        return this.idtCemiterio;
    }
    
    public void setIdtCemiterio(Integer idtCemiterio) {
        this.idtCemiterio = idtCemiterio;
    }

    
    @Column(name="nme_cemiterio", nullable=false, length=45)
    public String getNmeCemiterio() {
        return this.nmeCemiterio;
    }
    
    public void setNmeCemiterio(String nmeCemiterio) {
        this.nmeCemiterio = nmeCemiterio;
    }

    
    @Column(name="end_cemiterio", nullable=false, length=45)
    public String getEndCemiterio() {
        return this.endCemiterio;
    }
    
    public void setEndCemiterio(String endCemiterio) {
        this.endCemiterio = endCemiterio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbCemiterio")
    public Set<TbFalecido> getTbFalecidos() {
        return this.tbFalecidos;
    }
    
    public void setTbFalecidos(Set<TbFalecido> tbFalecidos) {
        this.tbFalecidos = tbFalecidos;
    }




}


