package model;
// Generated Oct 23, 2017 3:22:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TbFalecido generated by hbm2java
 */
@Entity
@Table(name="tb_falecido"
    ,catalog="mydb"
    , uniqueConstraints = @UniqueConstraint(columnNames="cpf_falecido") 
)
public class TbFalecido  implements java.io.Serializable {


     private Integer idtFalecido;
     private TbCemiterio tbCemiterio;
     private TbResponsavel tbResponsavel;
     private String nmeFalecido;
     private Date dtaObitoFalecido;
     private Date dtaNascFalecido;
     private String cpfFalecido;
     private String numSepulturaFalecido;
     private Set<TaContrato> taContratos = new HashSet<TaContrato>(0);
     private Set<TaCompra> taCompras = new HashSet<TaCompra>(0);

    public TbFalecido() {
    }

	
    public TbFalecido(TbCemiterio tbCemiterio, TbResponsavel tbResponsavel, String nmeFalecido, Date dtaObitoFalecido, String cpfFalecido) {
        this.tbCemiterio = tbCemiterio;
        this.tbResponsavel = tbResponsavel;
        this.nmeFalecido = nmeFalecido;
        this.dtaObitoFalecido = dtaObitoFalecido;
        this.cpfFalecido = cpfFalecido;
    }
    public TbFalecido(TbCemiterio tbCemiterio, TbResponsavel tbResponsavel, String nmeFalecido, Date dtaObitoFalecido, Date dtaNascFalecido, String cpfFalecido, String numSepulturaFalecido, Set<TaContrato> taContratos, Set<TaCompra> taCompras) {
       this.tbCemiterio = tbCemiterio;
       this.tbResponsavel = tbResponsavel;
       this.nmeFalecido = nmeFalecido;
       this.dtaObitoFalecido = dtaObitoFalecido;
       this.dtaNascFalecido = dtaNascFalecido;
       this.cpfFalecido = cpfFalecido;
       this.numSepulturaFalecido = numSepulturaFalecido;
       this.taContratos = taContratos;
       this.taCompras = taCompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_falecido", unique=true, nullable=false)
    public Integer getIdtFalecido() {
        return this.idtFalecido;
    }
    
    public void setIdtFalecido(Integer idtFalecido) {
        this.idtFalecido = idtFalecido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_cemiterio", nullable=false)
    public TbCemiterio getTbCemiterio() {
        return this.tbCemiterio;
    }
    
    public void setTbCemiterio(TbCemiterio tbCemiterio) {
        this.tbCemiterio = tbCemiterio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_responsavel", nullable=false)
    public TbResponsavel getTbResponsavel() {
        return this.tbResponsavel;
    }
    
    public void setTbResponsavel(TbResponsavel tbResponsavel) {
        this.tbResponsavel = tbResponsavel;
    }

    
    @Column(name="nme_falecido", nullable=false, length=55)
    public String getNmeFalecido() {
        return this.nmeFalecido;
    }
    
    public void setNmeFalecido(String nmeFalecido) {
        this.nmeFalecido = nmeFalecido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_obito_falecido", nullable=false, length=10)
    public Date getDtaObitoFalecido() {
        return this.dtaObitoFalecido;
    }
    
    public void setDtaObitoFalecido(Date dtaObitoFalecido) {
        this.dtaObitoFalecido = dtaObitoFalecido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_nasc_falecido", length=10)
    public Date getDtaNascFalecido() {
        return this.dtaNascFalecido;
    }
    
    public void setDtaNascFalecido(Date dtaNascFalecido) {
        this.dtaNascFalecido = dtaNascFalecido;
    }

    
    @Column(name="cpf_falecido", unique=true, nullable=false, length=11)
    public String getCpfFalecido() {
        return this.cpfFalecido;
    }
    
    public void setCpfFalecido(String cpfFalecido) {
        this.cpfFalecido = cpfFalecido;
    }

    
    @Column(name="num_sepultura_falecido", length=10)
    public String getNumSepulturaFalecido() {
        return this.numSepulturaFalecido;
    }
    
    public void setNumSepulturaFalecido(String numSepulturaFalecido) {
        this.numSepulturaFalecido = numSepulturaFalecido;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbFalecido")
    public Set<TaContrato> getTaContratos() {
        return this.taContratos;
    }
    
    public void setTaContratos(Set<TaContrato> taContratos) {
        this.taContratos = taContratos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbFalecido")
    public Set<TaCompra> getTaCompras() {
        return this.taCompras;
    }
    
    public void setTaCompras(Set<TaCompra> taCompras) {
        this.taCompras = taCompras;
    }




}


