package model;
// Generated Oct 23, 2017 3:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TbFornecedor generated by hbm2java
 */
@Entity
@Table(name="tb_fornecedor"
    ,catalog="mydb"
    , uniqueConstraints = @UniqueConstraint(columnNames="cpj_fornecedor") 
)
public class TbFornecedor  implements java.io.Serializable {


     private Integer idtFornecedor;
     private String nmeFornecedor;
     private String telFornecedor;
     private String cpjFornecedor;
     private Set<TbProduto> tbProdutos = new HashSet<TbProduto>(0);

    public TbFornecedor() {
    }

	
    public TbFornecedor(String nmeFornecedor, String telFornecedor, String cpjFornecedor) {
        this.nmeFornecedor = nmeFornecedor;
        this.telFornecedor = telFornecedor;
        this.cpjFornecedor = cpjFornecedor;
    }
    public TbFornecedor(String nmeFornecedor, String telFornecedor, String cpjFornecedor, Set<TbProduto> tbProdutos) {
       this.nmeFornecedor = nmeFornecedor;
       this.telFornecedor = telFornecedor;
       this.cpjFornecedor = cpjFornecedor;
       this.tbProdutos = tbProdutos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_fornecedor", unique=true, nullable=false)
    public Integer getIdtFornecedor() {
        return this.idtFornecedor;
    }
    
    public void setIdtFornecedor(Integer idtFornecedor) {
        this.idtFornecedor = idtFornecedor;
    }

    
    @Column(name="nme_fornecedor", nullable=false, length=45)
    public String getNmeFornecedor() {
        return this.nmeFornecedor;
    }
    
    public void setNmeFornecedor(String nmeFornecedor) {
        this.nmeFornecedor = nmeFornecedor;
    }

    
    @Column(name="tel_fornecedor", nullable=false, length=20)
    public String getTelFornecedor() {
        return this.telFornecedor;
    }
    
    public void setTelFornecedor(String telFornecedor) {
        this.telFornecedor = telFornecedor;
    }

    
    @Column(name="cpj_fornecedor", unique=true, nullable=false, length=14)
    public String getCpjFornecedor() {
        return this.cpjFornecedor;
    }
    
    public void setCpjFornecedor(String cpjFornecedor) {
        this.cpjFornecedor = cpjFornecedor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbFornecedor")
    public Set<TbProduto> getTbProdutos() {
        return this.tbProdutos;
    }
    
    public void setTbProdutos(Set<TbProduto> tbProdutos) {
        this.tbProdutos = tbProdutos;
    }




}


