package model;
// Generated Oct 23, 2017 3:22:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TbFuncionario generated by hbm2java
 */
@Entity
@Table(name="tb_funcionario"
    ,catalog="mydb"
    , uniqueConstraints = @UniqueConstraint(columnNames="eml_funcionario") 
)
public class TbFuncionario  implements java.io.Serializable {


     private int idtFuncionario;
     private TdFuncao tdFuncao;
     private String nmeFuncionario;
     private String funcFuncionario;
     private String matFuncionario;
     private String pwdFuncionario;
     private Date dtaNascFuncionario;
     private Date dtaAdmissaoFuncionario;
     private String emlFuncionario;
     private String telFuncionario;

    public TbFuncionario() {
    }

    public TbFuncionario(int idtFuncionario, TdFuncao tdFuncao, String nmeFuncionario, String funcFuncionario, String matFuncionario, String pwdFuncionario, Date dtaNascFuncionario, Date dtaAdmissaoFuncionario, String emlFuncionario, String telFuncionario) {
       this.idtFuncionario = idtFuncionario;
       this.tdFuncao = tdFuncao;
       this.nmeFuncionario = nmeFuncionario;
       this.funcFuncionario = funcFuncionario;
       this.matFuncionario = matFuncionario;
       this.pwdFuncionario = pwdFuncionario;
       this.dtaNascFuncionario = dtaNascFuncionario;
       this.dtaAdmissaoFuncionario = dtaAdmissaoFuncionario;
       this.emlFuncionario = emlFuncionario;
       this.telFuncionario = telFuncionario;
    }
   
     @Id 

    
    @Column(name="idt_funcionario", unique=true, nullable=false)
    public int getIdtFuncionario() {
        return this.idtFuncionario;
    }
    
    public void setIdtFuncionario(int idtFuncionario) {
        this.idtFuncionario = idtFuncionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_funcao", nullable=false)
    public TdFuncao getTdFuncao() {
        return this.tdFuncao;
    }
    
    public void setTdFuncao(TdFuncao tdFuncao) {
        this.tdFuncao = tdFuncao;
    }

    
    @Column(name="nme_funcionario", nullable=false, length=55)
    public String getNmeFuncionario() {
        return this.nmeFuncionario;
    }
    
    public void setNmeFuncionario(String nmeFuncionario) {
        this.nmeFuncionario = nmeFuncionario;
    }

    
    @Column(name="func_funcionario", nullable=false, length=45)
    public String getFuncFuncionario() {
        return this.funcFuncionario;
    }
    
    public void setFuncFuncionario(String funcFuncionario) {
        this.funcFuncionario = funcFuncionario;
    }

    
    @Column(name="mat_funcionario", nullable=false, length=6)
    public String getMatFuncionario() {
        return this.matFuncionario;
    }
    
    public void setMatFuncionario(String matFuncionario) {
        this.matFuncionario = matFuncionario;
    }

    
    @Column(name="pwd_funcionario", nullable=false, length=128)
    public String getPwdFuncionario() {
        return this.pwdFuncionario;
    }
    
    public void setPwdFuncionario(String pwdFuncionario) {
        this.pwdFuncionario = pwdFuncionario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_nasc_funcionario", nullable=false, length=10)
    public Date getDtaNascFuncionario() {
        return this.dtaNascFuncionario;
    }
    
    public void setDtaNascFuncionario(Date dtaNascFuncionario) {
        this.dtaNascFuncionario = dtaNascFuncionario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dta_admissao_funcionario", nullable=false, length=10)
    public Date getDtaAdmissaoFuncionario() {
        return this.dtaAdmissaoFuncionario;
    }
    
    public void setDtaAdmissaoFuncionario(Date dtaAdmissaoFuncionario) {
        this.dtaAdmissaoFuncionario = dtaAdmissaoFuncionario;
    }

    
    @Column(name="eml_funcionario", unique=true, nullable=false, length=50)
    public String getEmlFuncionario() {
        return this.emlFuncionario;
    }
    
    public void setEmlFuncionario(String emlFuncionario) {
        this.emlFuncionario = emlFuncionario;
    }

    
    @Column(name="tel_funcionario", nullable=false, length=20)
    public String getTelFuncionario() {
        return this.telFuncionario;
    }
    
    public void setTelFuncionario(String telFuncionario) {
        this.telFuncionario = telFuncionario;
    }




}


