package model;
// Generated Oct 23, 2017 3:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbProduto generated by hbm2java
 */
@Entity
@Table(name="tb_produto"
    ,catalog="mydb"
)
public class TbProduto  implements java.io.Serializable {


     private Integer idtProduto;
     private TbFornecedor tbFornecedor;
     private String nmeProduto;
     private String dscProduto;
     private Set<TaCompra> taCompras = new HashSet<TaCompra>(0);

    public TbProduto() {
    }

	
    public TbProduto(TbFornecedor tbFornecedor, String nmeProduto, String dscProduto) {
        this.tbFornecedor = tbFornecedor;
        this.nmeProduto = nmeProduto;
        this.dscProduto = dscProduto;
    }
    public TbProduto(TbFornecedor tbFornecedor, String nmeProduto, String dscProduto, Set<TaCompra> taCompras) {
       this.tbFornecedor = tbFornecedor;
       this.nmeProduto = nmeProduto;
       this.dscProduto = dscProduto;
       this.taCompras = taCompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_produto", unique=true, nullable=false)
    public Integer getIdtProduto() {
        return this.idtProduto;
    }
    
    public void setIdtProduto(Integer idtProduto) {
        this.idtProduto = idtProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_fornecedor", nullable=false)
    public TbFornecedor getTbFornecedor() {
        return this.tbFornecedor;
    }
    
    public void setTbFornecedor(TbFornecedor tbFornecedor) {
        this.tbFornecedor = tbFornecedor;
    }

    
    @Column(name="nme_produto", nullable=false, length=45)
    public String getNmeProduto() {
        return this.nmeProduto;
    }
    
    public void setNmeProduto(String nmeProduto) {
        this.nmeProduto = nmeProduto;
    }

    
    @Column(name="dsc_produto", nullable=false, length=250)
    public String getDscProduto() {
        return this.dscProduto;
    }
    
    public void setDscProduto(String dscProduto) {
        this.dscProduto = dscProduto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbProduto")
    public Set<TaCompra> getTaCompras() {
        return this.taCompras;
    }
    
    public void setTaCompras(Set<TaCompra> taCompras) {
        this.taCompras = taCompras;
    }




}


