package model;
// Generated Oct 23, 2017 3:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TbResponsavel generated by hbm2java
 */
@Entity
@Table(name="tb_responsavel"
    ,catalog="mydb"
    , uniqueConstraints = @UniqueConstraint(columnNames="cpf_responsavel") 
)
public class TbResponsavel  implements java.io.Serializable {


     private Integer idtResponsavel;
     private String nmeResponsavel;
     private String telResponsavel;
     private String grauResponsavel;
     private String cpfResponsavel;
     private String emlResponsavel;
     private String endResponsavel;
     private Set<TbFalecido> tbFalecidos = new HashSet<TbFalecido>(0);

    public TbResponsavel() {
    }

	
    public TbResponsavel(String nmeResponsavel, String telResponsavel, String grauResponsavel, String cpfResponsavel) {
        this.nmeResponsavel = nmeResponsavel;
        this.telResponsavel = telResponsavel;
        this.grauResponsavel = grauResponsavel;
        this.cpfResponsavel = cpfResponsavel;
    }
    public TbResponsavel(String nmeResponsavel, String telResponsavel, String grauResponsavel, String cpfResponsavel, String emlResponsavel, String endResponsavel, Set<TbFalecido> tbFalecidos) {
       this.nmeResponsavel = nmeResponsavel;
       this.telResponsavel = telResponsavel;
       this.grauResponsavel = grauResponsavel;
       this.cpfResponsavel = cpfResponsavel;
       this.emlResponsavel = emlResponsavel;
       this.endResponsavel = endResponsavel;
       this.tbFalecidos = tbFalecidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_responsavel", unique=true, nullable=false)
    public Integer getIdtResponsavel() {
        return this.idtResponsavel;
    }
    
    public void setIdtResponsavel(Integer idtResponsavel) {
        this.idtResponsavel = idtResponsavel;
    }

    
    @Column(name="nme_responsavel", nullable=false, length=55)
    public String getNmeResponsavel() {
        return this.nmeResponsavel;
    }
    
    public void setNmeResponsavel(String nmeResponsavel) {
        this.nmeResponsavel = nmeResponsavel;
    }

    
    @Column(name="tel_responsavel", nullable=false, length=20)
    public String getTelResponsavel() {
        return this.telResponsavel;
    }
    
    public void setTelResponsavel(String telResponsavel) {
        this.telResponsavel = telResponsavel;
    }

    
    @Column(name="grau_responsavel", nullable=false, length=45)
    public String getGrauResponsavel() {
        return this.grauResponsavel;
    }
    
    public void setGrauResponsavel(String grauResponsavel) {
        this.grauResponsavel = grauResponsavel;
    }

    
    @Column(name="cpf_responsavel", unique=true, nullable=false, length=11)
    public String getCpfResponsavel() {
        return this.cpfResponsavel;
    }
    
    public void setCpfResponsavel(String cpfResponsavel) {
        this.cpfResponsavel = cpfResponsavel;
    }

    
    @Column(name="eml_responsavel", length=50)
    public String getEmlResponsavel() {
        return this.emlResponsavel;
    }
    
    public void setEmlResponsavel(String emlResponsavel) {
        this.emlResponsavel = emlResponsavel;
    }

    
    @Column(name="end_responsavel", length=45)
    public String getEndResponsavel() {
        return this.endResponsavel;
    }
    
    public void setEndResponsavel(String endResponsavel) {
        this.endResponsavel = endResponsavel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbResponsavel")
    public Set<TbFalecido> getTbFalecidos() {
        return this.tbFalecidos;
    }
    
    public void setTbFalecidos(Set<TbFalecido> tbFalecidos) {
        this.tbFalecidos = tbFalecidos;
    }




}


