package model;
// Generated Oct 23, 2017 3:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbServico generated by hbm2java
 */
@Entity
@Table(name="tb_servico"
    ,catalog="mydb"
)
public class TbServico  implements java.io.Serializable {


     private Integer idtServico;
     private TdFuncao tdFuncao;
     private String nmeServico;
     private String sglServico;
     private Set<TaContrato> taContratos = new HashSet<TaContrato>(0);

    public TbServico() {
    }

	
    public TbServico(TdFuncao tdFuncao, String nmeServico, String sglServico) {
        this.tdFuncao = tdFuncao;
        this.nmeServico = nmeServico;
        this.sglServico = sglServico;
    }
    public TbServico(TdFuncao tdFuncao, String nmeServico, String sglServico, Set<TaContrato> taContratos) {
       this.tdFuncao = tdFuncao;
       this.nmeServico = nmeServico;
       this.sglServico = sglServico;
       this.taContratos = taContratos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_servico", unique=true, nullable=false)
    public Integer getIdtServico() {
        return this.idtServico;
    }
    
    public void setIdtServico(Integer idtServico) {
        this.idtServico = idtServico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cod_funcao", nullable=false)
    public TdFuncao getTdFuncao() {
        return this.tdFuncao;
    }
    
    public void setTdFuncao(TdFuncao tdFuncao) {
        this.tdFuncao = tdFuncao;
    }

    
    @Column(name="nme_servico", nullable=false, length=45)
    public String getNmeServico() {
        return this.nmeServico;
    }
    
    public void setNmeServico(String nmeServico) {
        this.nmeServico = nmeServico;
    }

    
    @Column(name="sgl_servico", nullable=false, length=6)
    public String getSglServico() {
        return this.sglServico;
    }
    
    public void setSglServico(String sglServico) {
        this.sglServico = sglServico;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tbServico")
    public Set<TaContrato> getTaContratos() {
        return this.taContratos;
    }
    
    public void setTaContratos(Set<TaContrato> taContratos) {
        this.taContratos = taContratos;
    }




}


