package model;
// Generated Oct 23, 2017 3:22:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TdFuncao generated by hbm2java
 */
@Entity
@Table(name="td_funcao"
    ,catalog="mydb"
)
public class TdFuncao  implements java.io.Serializable {


     private Integer idtFuncao;
     private String nmeFuncao;
     private Set<TbServico> tbServicos = new HashSet<TbServico>(0);
     private Set<TbFuncionario> tbFuncionarios = new HashSet<TbFuncionario>(0);

    public TdFuncao() {
    }

	
    public TdFuncao(String nmeFuncao) {
        this.nmeFuncao = nmeFuncao;
    }
    public TdFuncao(String nmeFuncao, Set<TbServico> tbServicos, Set<TbFuncionario> tbFuncionarios) {
       this.nmeFuncao = nmeFuncao;
       this.tbServicos = tbServicos;
       this.tbFuncionarios = tbFuncionarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idt_funcao", unique=true, nullable=false)
    public Integer getIdtFuncao() {
        return this.idtFuncao;
    }
    
    public void setIdtFuncao(Integer idtFuncao) {
        this.idtFuncao = idtFuncao;
    }

    
    @Column(name="nme_funcao", nullable=false, length=45)
    public String getNmeFuncao() {
        return this.nmeFuncao;
    }
    
    public void setNmeFuncao(String nmeFuncao) {
        this.nmeFuncao = nmeFuncao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdFuncao")
    public Set<TbServico> getTbServicos() {
        return this.tbServicos;
    }
    
    public void setTbServicos(Set<TbServico> tbServicos) {
        this.tbServicos = tbServicos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tdFuncao")
    public Set<TbFuncionario> getTbFuncionarios() {
        return this.tbFuncionarios;
    }
    
    public void setTbFuncionarios(Set<TbFuncionario> tbFuncionarios) {
        this.tbFuncionarios = tbFuncionarios;
    }




}


